sudo: required

services:
  - docker

before_install:
  - docker build --no-cache -t unidata/ramadda-docker:latest .
  - docker run --name ramadda -v `pwd`/.travis:/travis -d -p 8080:8080 unidata/ramadda-docker:latest
  - curl -o /dev/null http://127.0.0.1:8080/repository || true
  # Give chance for RAMADDA to fire up
  - nc -z -w300 127.0.0.1 8080
  - for i in {1..5}; do curl -o /dev/null http://127.0.0.1:8080/repository/ && break || (echo sleeping 15... && sleep 15); done

script:
  - ./.travis/test.sh
