version: '3'

services:

  ramadda:
    image: unidata/ramadda-docker:latest
    container_name: ramadda
    ports:
      - "80:8080"
    volumes:
      # change default to where you would like the repository directory to live.
      - ./repository:/data/repository
      - ./tomcat-logs/:/usr/local/tomcat/logs
      - ./ramadda-logs/:/data/repository/logs
    env_file:
      - "compose.env"
